apiVersion: v1
kind: Secret
metadata:
  name: secreto-mongodb
  namespace: monitoreo
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "adminlogistica"
  MONGO_INITDB_ROOT_PASSWORD: "ClaveMongo_789!"
